"use client"

import { motion, AnimatePresence } from "framer-motion"
import { 
  GraduationCap, 
  LogOut, 
  Search, 
  FileText, 
  Download, 
  User,
  BookOpen,
  Calculator,
  FlaskConical,
  Languages,
  Plus,
  CheckCircle,
  AlertCircle,
  Loader2,
  TrendingUp
} from "lucide-react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { User as UserType, Student } from "@/lib/types"
import { useState } from "react"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

interface DashboardPageProps {
  user: UserType
  onLogout: () => void
  formData: {
    name: string
    rollNumber: string
    math: string
    science: string
    english: string
  }
  onFormChange: (e: React.ChangeEvent<HTMLInputElement>) => void
  onAddStudent: (e: React.FormEvent) => void
  searchRoll: string
  onSearchChange: (value: string) => void
  onSearchStudent: (e: React.FormEvent) => void
  selectedStudent: Student | null
  message: string
}

const gradeColors: Record<string, string> = {
  "A+": "text-green-400",
  "A": "text-green-400",
  "B": "text-blue-400",
  "C": "text-yellow-400",
  "D": "text-orange-400",
  "F": "text-red-400",
}

const gradingScale = [
  { grade: "A+", range: "90 - 100", color: "bg-green-500/20 text-green-400" },
  { grade: "A", range: "80 - 89", color: "bg-green-500/20 text-green-400" },
  { grade: "B", range: "70 - 79", color: "bg-blue-500/20 text-blue-400" },
  { grade: "C", range: "60 - 69", color: "bg-yellow-500/20 text-yellow-400" },
  { grade: "D", range: "50 - 59", color: "bg-orange-500/20 text-orange-400" },
  { grade: "F", range: "Below 50", color: "bg-red-500/20 text-red-400" },
]

export function DashboardPage({
  user,
  onLogout,
  formData,
  onFormChange,
  onAddStudent,
  searchRoll,
  onSearchChange,
  onSearchStudent,
  selectedStudent,
  message,
}: DashboardPageProps) {
  const [isAddingStudent, setIsAddingStudent] = useState(false)
  const [isSearching, setIsSearching] = useState(false)

  const isTeacher = user.role === 'teacher'

  const handleAddStudent = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsAddingStudent(true)
    await onAddStudent(e)
    setIsAddingStudent(false)
  }

  const handleSearchStudent = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSearching(true)
    await onSearchStudent(e)
    setIsSearching(false)
  }

  const generatePDF = (student: Student) => {
    const doc = new jsPDF()
    const rollNo = student.rollNumber || ''
    const maths = student.math ?? 0
    const science = student.science ?? 0
    const english = student.english ?? 0
    const total = student.total ?? maths + science + english
    const percentage = student.average ?? 0

    doc.setFontSize(16)
    doc.text('AFRAZ College of Technology', 105, 20, { align: 'center' })
    doc.setFontSize(10)
    doc.text('451 Innovation Avenue, Tech City, TX 75201', 105, 26, { align: 'center' })
    doc.text('Phone: +1 800 123 4567 | Email: info@afraztech.edu', 105, 31, { align: 'center' })
    doc.setLineWidth(0.5)
    doc.line(20, 34, 190, 34)

    doc.setFontSize(14)
    doc.text('Student Report Card', 105, 44, { align: 'center' })

    doc.setFontSize(11)
    doc.text(`Generated by: ${user?.name || 'School Report System'}`, 20, 54)
    doc.text(`Role: ${user?.role || ''}`, 20, 60)
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 60)

    doc.text(`Student Name: ${student.name}`, 20, 74)
    doc.text(`Roll Number: ${rollNo}`, 20, 80)
    doc.text(`Class: ${student.className || '10th Grade'}`, 20, 86)
    doc.text(`Section: ${student.section || 'A'}`, 20, 92)

    autoTable(doc, {
      startY: 100,
      head: [['Subject', 'Marks']],
      body: [
        ['Mathematics', maths],
        ['Science', science],
        ['English', english],
      ],
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] },
    })

    doc.setFontSize(11)
    doc.text(`Total: ${total}`, 20, 140)
    doc.text(`Percentage: ${Number(percentage).toFixed(2)}%`, 20, 148)
    doc.text(`Grade: ${student.grade}`, 20, 156)
    doc.text(`Remarks: ${student.remarks}`, 20, 164)

    doc.setFontSize(10)
    doc.text('Grading Scale', 20, 178)
    doc.text('A+ : 90 - 100', 20, 186)
    doc.text('A  : 80 - 89', 20, 192)
    doc.text('B  : 70 - 79', 20, 198)
    doc.text('C  : 60 - 69', 20, 204)
    doc.text('D  : 50 - 59', 20, 210)
    doc.text('F  : Below 50', 20, 216)

    doc.save(`${student.name || 'student'}_ReportCard.pdf`)
  }

  return (
    <div className="min-h-screen gradient-bg">
      {/* Grid overlay */}
      <div className="fixed inset-0 grid-pattern opacity-30 pointer-events-none" />

      <div className="relative">
        {/* Header */}
        <motion.header
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="border-b border-border/50 backdrop-blur-xl bg-background/50 sticky top-0 z-50"
        >
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${
                isTeacher ? 'bg-primary/20' : 'bg-chart-2/20'
              }`}>
                <GraduationCap className={`w-6 h-6 ${isTeacher ? 'text-primary' : 'text-chart-2'}`} />
              </div>
              <div>
                <h1 className="font-semibold text-foreground">Dashboard</h1>
                <p className="text-xs text-muted-foreground capitalize">{user.role} Portal</p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2 text-sm">
                <div className="w-8 h-8 rounded-full bg-secondary flex items-center justify-center">
                  <User className="w-4 h-4 text-foreground" />
                </div>
                <span className="text-muted-foreground hidden sm:inline">{user.name}</span>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={onLogout}
                className="gap-2"
              >
                <LogOut className="w-4 h-4" />
                <span className="hidden sm:inline">Logout</span>
              </Button>
            </div>
          </div>
        </motion.header>

        {/* Main Content */}
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Welcome Section */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="mb-8"
          >
            <h2 className="text-3xl font-bold text-foreground mb-2">
              Welcome back, {user.name}
            </h2>
            <p className="text-muted-foreground">
              {isTeacher 
                ? 'Manage student records and generate report cards.'
                : 'Search and download your academic report card.'
              }
            </p>
          </motion.div>

          {/* Dashboard Grid */}
          <div className="grid lg:grid-cols-2 gap-6">
            {/* Add Student Form - Teachers Only */}
            {isTeacher && (
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.5, delay: 0.1 }}
                className="glass-card rounded-2xl p-6"
              >
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-xl bg-primary/20 flex items-center justify-center">
                    <Plus className="w-5 h-5 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-foreground">Add / Update Marks</h3>
                    <p className="text-sm text-muted-foreground">Enter student academic details</p>
                  </div>
                </div>

                <form onSubmit={handleAddStudent} className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="name" className="text-sm text-muted-foreground">
                        Student Name
                      </Label>
                      <Input
                        id="name"
                        name="name"
                        type="text"
                        value={formData.name}
                        onChange={onFormChange}
                        required
                        className="bg-input border-border"
                        placeholder="John Doe"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="rollNumber" className="text-sm text-muted-foreground">
                        Roll Number
                      </Label>
                      <Input
                        id="rollNumber"
                        name="rollNumber"
                        type="text"
                        value={formData.rollNumber}
                        onChange={onFormChange}
                        required
                        className="bg-input border-border"
                        placeholder="2025001"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="math" className="text-sm text-muted-foreground flex items-center gap-2">
                        <Calculator className="w-3 h-3" />
                        Mathematics
                      </Label>
                      <Input
                        id="math"
                        name="math"
                        type="number"
                        min="0"
                        max="100"
                        value={formData.math}
                        onChange={onFormChange}
                        required
                        className="bg-input border-border"
                        placeholder="85"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="science" className="text-sm text-muted-foreground flex items-center gap-2">
                        <FlaskConical className="w-3 h-3" />
                        Science
                      </Label>
                      <Input
                        id="science"
                        name="science"
                        type="number"
                        min="0"
                        max="100"
                        value={formData.science}
                        onChange={onFormChange}
                        required
                        className="bg-input border-border"
                        placeholder="90"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="english" className="text-sm text-muted-foreground flex items-center gap-2">
                        <Languages className="w-3 h-3" />
                        English
                      </Label>
                      <Input
                        id="english"
                        name="english"
                        type="number"
                        min="0"
                        max="100"
                        value={formData.english}
                        onChange={onFormChange}
                        required
                        className="bg-input border-border"
                        placeholder="88"
                      />
                    </div>
                  </div>

                  <Button
                    type="submit"
                    disabled={isAddingStudent}
                    className="w-full bg-primary hover:bg-primary/90 text-primary-foreground"
                  >
                    {isAddingStudent ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Saving...
                      </>
                    ) : (
                      <>
                        <FileText className="w-4 h-4 mr-2" />
                        Save Report
                      </>
                    )}
                  </Button>
                </form>
              </motion.div>
            )}

            {/* Search Section */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className={`glass-card rounded-2xl p-6 ${!isTeacher ? 'lg:col-span-2' : ''}`}
            >
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 rounded-xl bg-chart-2/20 flex items-center justify-center">
                  <Search className="w-5 h-5 text-chart-2" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground">
                    {isTeacher ? 'Search Student Marks' : 'Find Your Report Card'}
                  </h3>
                  <p className="text-sm text-muted-foreground">Enter roll number to search</p>
                </div>
              </div>

              <form onSubmit={handleSearchStudent} className="space-y-4">
                <div className="flex gap-4">
                  <div className="flex-1">
                    <Input
                      type="text"
                      value={searchRoll}
                      onChange={(e) => onSearchChange(e.target.value)}
                      required
                      className="bg-input border-border h-11"
                      placeholder="Enter Roll Number (e.g., 2025001)"
                    />
                  </div>
                  <Button
                    type="submit"
                    disabled={isSearching}
                    className="h-11 px-6 bg-chart-2 hover:bg-chart-2/90 text-primary-foreground"
                  >
                    {isSearching ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      <Search className="w-4 h-4" />
                    )}
                  </Button>
                </div>
              </form>

              {/* Message */}
              <AnimatePresence>
                {message && (
                  <motion.div
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    className={`flex items-center gap-2 text-sm rounded-lg p-3 mt-4 ${
                      message.includes('found') || message.includes('success')
                        ? 'bg-green-500/10 text-green-400'
                        : 'bg-yellow-500/10 text-yellow-400'
                    }`}
                  >
                    {message.includes('found') || message.includes('success') ? (
                      <CheckCircle className="w-4 h-4" />
                    ) : (
                      <AlertCircle className="w-4 h-4" />
                    )}
                    {message}
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Student Result Card */}
              <AnimatePresence>
                {selectedStudent && (
                  <motion.div
                    initial={{ opacity: 0, y: 20, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: 20, scale: 0.95 }}
                    transition={{ duration: 0.3 }}
                    className="mt-6 bg-secondary/30 rounded-xl p-6 border border-border"
                  >
                    {/* Student Header */}
                    <div className="flex items-start justify-between mb-6">
                      <div className="flex items-center gap-4">
                        <div className="w-14 h-14 rounded-xl bg-primary/20 flex items-center justify-center">
                          <User className="w-7 h-7 text-primary" />
                        </div>
                        <div>
                          <h4 className="text-lg font-semibold text-foreground">{selectedStudent.name}</h4>
                          <p className="text-sm text-muted-foreground">Roll No: {selectedStudent.rollNumber}</p>
                        </div>
                      </div>
                      <div className={`px-4 py-2 rounded-full font-bold text-lg ${
                        gradeColors[selectedStudent.grade] || 'text-foreground'
                      } bg-secondary`}>
                        {selectedStudent.grade}
                      </div>
                    </div>

                    {/* Marks Grid */}
                    <div className="grid grid-cols-3 gap-4 mb-6">
                      <div className="bg-background/50 rounded-xl p-4 text-center">
                        <Calculator className="w-5 h-5 text-primary mx-auto mb-2" />
                        <div className="text-2xl font-bold text-foreground">{selectedStudent.math}</div>
                        <div className="text-xs text-muted-foreground">Mathematics</div>
                      </div>
                      <div className="bg-background/50 rounded-xl p-4 text-center">
                        <FlaskConical className="w-5 h-5 text-chart-2 mx-auto mb-2" />
                        <div className="text-2xl font-bold text-foreground">{selectedStudent.science}</div>
                        <div className="text-xs text-muted-foreground">Science</div>
                      </div>
                      <div className="bg-background/50 rounded-xl p-4 text-center">
                        <Languages className="w-5 h-5 text-chart-3 mx-auto mb-2" />
                        <div className="text-2xl font-bold text-foreground">{selectedStudent.english}</div>
                        <div className="text-xs text-muted-foreground">English</div>
                      </div>
                    </div>

                    {/* Summary */}
                    <div className="grid grid-cols-2 gap-4 mb-6">
                      <div className="bg-background/50 rounded-xl p-4">
                        <div className="flex items-center gap-2 text-muted-foreground text-sm mb-1">
                          <BookOpen className="w-4 h-4" />
                          Total Marks
                        </div>
                        <div className="text-2xl font-bold text-foreground">{selectedStudent.total}/300</div>
                      </div>
                      <div className="bg-background/50 rounded-xl p-4">
                        <div className="flex items-center gap-2 text-muted-foreground text-sm mb-1">
                          <TrendingUp className="w-4 h-4" />
                          Average
                        </div>
                        <div className="text-2xl font-bold text-foreground">{selectedStudent.average.toFixed(2)}%</div>
                      </div>
                    </div>

                    {/* Remarks */}
                    <div className="bg-background/50 rounded-xl p-4 mb-6">
                      <div className="text-sm text-muted-foreground mb-1">Remarks</div>
                      <div className="text-foreground font-medium">{selectedStudent.remarks}</div>
                    </div>

                    {/* Download Button */}
                    <Button
                      onClick={() => generatePDF(selectedStudent)}
                      className="w-full bg-primary hover:bg-primary/90 text-primary-foreground"
                    >
                      <Download className="w-4 h-4 mr-2" />
                      Download Report Card (PDF)
                    </Button>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>

            {/* Grading Guide */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              className="lg:col-span-2 glass-card rounded-2xl p-6"
            >
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 rounded-xl bg-chart-3/20 flex items-center justify-center">
                  <BookOpen className="w-5 h-5 text-chart-3" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground">Grading Scale</h3>
                  <p className="text-sm text-muted-foreground">Academic performance evaluation criteria</p>
                </div>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
                {gradingScale.map((item, index) => (
                  <motion.div
                    key={item.grade}
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.3, delay: 0.4 + index * 0.05 }}
                    className={`${item.color} rounded-xl p-4 text-center`}
                  >
                    <div className="text-2xl font-bold mb-1">{item.grade}</div>
                    <div className="text-sm opacity-80">{item.range}</div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          </div>
        </main>
      </div>
    </div>
  )
}
